Resolved value error on compiling discriminator
The error was due to dynamic index of the loss tensor, which had the shape (?1), which can't be sliced in pythonic way, so we used tf.split

ValueError: slice index 4 of dimension 1 out of bounds. for 'loss_2/dense_34_loss/Discriminator_Loss/strided_slice_1' (op: 'StridedSlice') with input shapes: [?,1], [2], [2], [2] and with computed input tensors: input[1] = <2 4>, input[2] = <3 5>, input[3] = <1 1>.